
# ------------------------------------------------------------------------------
# Directorios de trabajo
# ------------------------------------------------------------------------------
dir :  
  base : "/home/<usuario>/" # Aqui se debe colocar el directorio base 
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Archivo RData a procesar
# ------------------------------------------------------------------------------
input.file : workshop_local # Nombre del archivo con los datos sintéticos generados
# No debe incluir la extensión, sólo el nombre.
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Variables a validar
# ------------------------------------------------------------------------------
variables : [ 'prcp', 'tmin', 'tmax' ] # Variables a validar. Se debe respestar 
# estos nombres.
# ------------------------------------------------------------------------------
 
# ------------------------------------------------------------------------------
# Umbral de precipitación
# ------------------------------------------------------------------------------
umbral.precipitacion: 0.1 # Umbral de definición de día lluvioso
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Archivo donde se guarda el resporte
# ------------------------------------------------------------------------------
output.file : "ValidationReport_workshop.html" # Nombre del archivo de salida
# ------------------------------------------------------------------------------
